spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalsystem
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update
server.address=0.0.0.0

our.very.very.very.secret.key=secret

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http.converter=DEBUG
