package com.example.hospital.logging;

public enum EventType {
    //AUTH EVENTS
    SUCCESSFUL_LOGIN,
    FAILED_LOGIN,
    PASSWORD_CHANGE_REQUESTS,
    PASSWORD_RESET_ATTEMPTS,
    UNAUTHORIZED_ACCESS_ATTEMPT,

    //DATA ACCESS EVENTS
    ROLE_ESCALATION_EVENT,
    ACCESS_GRANTED_SENSITIVE_RESOURCES,
    SENSITIVE_DATA_ACCESS,
    DATA_MODIFICATION,
    FILE_UPLOAD,
    FILE_DOWNLOAD,
    DATA_DELETION,
    //NETWORK EVENTS
    SUSPICIOUS_IP_ADDRESS,
    GEOLOCATION_CHANGES,
    PORT_SCANNING,
    UNUSUAL_TRAFFIC_SPIKES,
    API_RATE_LIMIT_EXCEEDED,
    CROSS_SITE_SCRIPTING_ATTEMPT,
    INVALID_API_REQUESTS,
    //USER ACTIVITY
    SUSPICIOUS_USER_BEHAVIOUR,
    IDLE_SESSION,
    MULTIPLE_FAILED_ACTIONS,
    //INFRASTRUCTURE EVENTS
    DISK_SPACE_ALERT,
    MEMORY_SPIKES,
    //RESOURCE USAGE
    HIGH_DATABASE_LOAD,
    ABNORMAL_STORAGE_USAGE
}
